/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/@ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["ping__ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get an access token and a refresh token */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new pair */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session of a refresh token */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The account of the caller */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the password (ends every other session) */
        post: operations["change_password_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the accounts */
        get: operations["list_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an account (soft delete: kept in the database, its watches paused) */
        delete: operations["delete_user_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Change the role of an account, or disable it */
        patch: operations["update_user_users__user_id__patch"];
        trace?: never;
    };
    "/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my watches */
        get: operations["list_all_watches_get"];
        put?: never;
        /** Create a watch */
        post: operations["create_watches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a watch */
        get: operations["read_watches__watch_id__get"];
        put?: never;
        post?: never;
        /** Delete a watch */
        delete: operations["delete_watches__watch_id__delete"];
        options?: never;
        head?: never;
        /** Update a watch */
        patch: operations["update_watches__watch_id__patch"];
        trace?: never;
    };
    "/watches/{watch_id}/mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the mentions of a watch */
        get: operations["list_mentions_watches__watch_id__mentions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sentiment and emotion statistics of a watch */
        get: operations["stats_watches__watch_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sentiment by district of Côte d'Ivoire */
        get: operations["places_watches__watch_id__places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The words that come back the most, with their sentiment */
        get: operations["themes_watches__watch_id__themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts raised for a watch */
        get: operations["list_for_watch_watches__watch_id__alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watches/{watch_id}/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark an alert as handled */
        post: operations["acknowledge_watches__watch_id__alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: string;
            /** Watch Id */
            watch_id: string;
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Mentions */
            mentions: number;
            /** Negative */
            negative: number;
            /** Negative Share */
            negative_share: number;
            /** Threshold Share */
            threshold_share: number;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
            /** Acknowledged At */
            acknowledged_at: string | null;
        };
        /** BucketOut */
        BucketOut: {
            /** Key */
            key: string;
            counts: components["schemas"]["CountsOut"];
        };
        /** CountsOut */
        CountsOut: {
            /** Total */
            total: number;
            /** Positive */
            positive: number;
            /** Neutral */
            neutral: number;
            /** Negative */
            negative: number;
            /** Negative Share */
            negative_share: number;
        };
        /**
         * Emotion
         * @enum {string}
         */
        Emotion: "joy" | "anger" | "fear" | "sadness" | "trust";
        /**
         * GroupBy
         * @enum {string}
         */
        GroupBy: "day" | "source" | "language";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MentionOut */
        MentionOut: {
            /** Id */
            id: string;
            source: components["schemas"]["SourceKind"];
            /** Url */
            url: string | null;
            /** Text */
            text: string;
            /** Author Ref */
            author_ref: string | null;
            /**
             * Venue
             * @description Where it was found: publication, page, channel or hashtag
             */
            venue?: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Language */
            language: string;
            sentiment: components["schemas"]["SentimentLabel"];
            /** Sentiment Scores */
            sentiment_scores: {
                [key: string]: number;
            };
            emotion: components["schemas"]["Emotion"] | null;
            /** Likes */
            likes: number;
            /** Shares */
            shares: number;
            /** Views */
            views: number;
            /** Comments */
            comments: number;
        };
        /** PageOut[AlertOut] */
        PageOut_AlertOut_: {
            /** Items */
            items: components["schemas"]["AlertOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PageOut[MentionOut] */
        PageOut_MentionOut_: {
            /** Items */
            items: components["schemas"]["MentionOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PageOut[UserOut] */
        PageOut_UserOut_: {
            /** Items */
            items: components["schemas"]["UserOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PageOut[WatchOut] */
        PageOut_WatchOut_: {
            /** Items */
            items: components["schemas"]["WatchOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PasswordChangeIn */
        PasswordChangeIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PlaceOut */
        PlaceOut: {
            /** District */
            district: string;
            counts: components["schemas"]["CountsOut"];
        };
        /** PlacesOut */
        PlacesOut: {
            /** Districts */
            districts: components["schemas"]["PlaceOut"][];
            /**
             * Located
             * @description Conversations that name a district or one of its towns
             */
            located: number;
            /**
             * Analyzed
             * @description Conversations read (the most recent of the period, at most 5000)
             */
            analyzed: number;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Email */
            email: string;
            /**
             * Password
             * @description Length set by MIN_PASSWORD_LENGTH and MAX_PASSWORD_LENGTH
             */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "user";
        /**
         * SentimentLabel
         * @enum {string}
         */
        SentimentLabel: "positive" | "neutral" | "negative";
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * SourceKind
         * @description Where a mention comes from. Shared vocabulary of watches, collection and mentions.
         * @enum {string}
         */
        SourceKind: "facebook" | "instagram" | "youtube" | "bluesky" | "news" | "gdelt";
        /** StatsOut */
        StatsOut: {
            totals: components["schemas"]["CountsOut"];
            /** Buckets */
            buckets: components["schemas"]["BucketOut"][];
            /** Emotions */
            emotions: {
                [key: string]: number;
            };
        };
        /** ThemeOut */
        ThemeOut: {
            /** Term */
            term: string;
            /**
             * Mentions
             * @description Conversations that use the word
             */
            mentions: number;
            /** Negative */
            negative: number;
            /** Neutral */
            neutral: number;
            /** Positive */
            positive: number;
        };
        /** ThemesOut */
        ThemesOut: {
            /** Themes */
            themes: components["schemas"]["ThemeOut"][];
            /** Analyzed */
            analyzed: number;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
            /**
             * Expires In
             * @description Lifetime of the access token, in seconds
             */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            role: components["schemas"]["Role"];
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
            /** Deleted At */
            deleted_at: string | null;
        };
        /** UserUpdateIn */
        UserUpdateIn: {
            role?: components["schemas"]["Role"] | null;
            /** Active */
            active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchCreate */
        WatchCreate: {
            /** Name */
            name: string;
            /** Keywords */
            keywords: string[];
            /** Sources */
            sources: components["schemas"]["SourceKind"][];
            /**
             * Languages
             * @default [
             *       "fr"
             *     ]
             */
            languages: string[];
            /**
             * Countries
             * @default [
             *       "CI"
             *     ]
             */
            countries: string[];
            /**
             * Frequency Minutes
             * @description One of (15, 60, 360, 1440)
             * @default 60
             */
            frequency_minutes: number;
            /**
             * Alert Negative Share
             * @default 0.4
             */
            alert_negative_share: number;
            /**
             * Alert Min Mentions
             * @default 20
             */
            alert_min_mentions: number;
        };
        /** WatchOut */
        WatchOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Keywords */
            keywords: string[];
            /** Sources */
            sources: components["schemas"]["SourceKind"][];
            /** Languages */
            languages: string[];
            /** Countries */
            countries: string[];
            /** Frequency Minutes */
            frequency_minutes: number;
            /** Alert Negative Share */
            alert_negative_share: number;
            /** Alert Min Mentions */
            alert_min_mentions: number;
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WatchSort
         * @enum {string}
         */
        WatchSort: "created" | "name";
        /** WatchUpdate */
        WatchUpdate: {
            /** Name */
            name?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Sources */
            sources?: components["schemas"]["SourceKind"][] | null;
            /** Languages */
            languages?: string[] | null;
            /** Countries */
            countries?: string[] | null;
            /** Frequency Minutes */
            frequency_minutes?: number | null;
            /** Alert Negative Share */
            alert_negative_share?: number | null;
            /** Alert Min Mentions */
            alert_min_mentions?: number | null;
            /** Active */
            active?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping__ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    change_password_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                /** @description Email contains */
                search?: string | null;
                /** @description Also list the deleted accounts */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_watches_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                /** @description Filter by name */
                search?: string | null;
                /** @description Only the active watches (true) or the paused ones (false) */
                active?: boolean | null;
                /** @description Created on or after this day */
                created_from?: string | null;
                /** @description Created on or before this day */
                created_to?: string | null;
                /** @description Sort by creation date or by name */
                sort?: components["schemas"]["WatchSort"];
                /** @description Direction of the sort */
                order?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut_WatchOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_watches__watch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watches__watch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watches__watch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mentions_watches__watch_id__mentions_get: {
        parameters: {
            query?: {
                source?: components["schemas"]["SourceKind"] | null;
                language?: string | null;
                sentiment?: components["schemas"]["SentimentLabel"] | null;
                emotion?: components["schemas"]["Emotion"] | null;
                /** @description Published at or after (ISO 8601) */
                start?: string | null;
                /** @description Published before (ISO 8601) */
                end?: string | null;
                /** @description Text contains */
                q?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut_MentionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_watches__watch_id__stats_get: {
        parameters: {
            query?: {
                group_by?: components["schemas"]["GroupBy"];
                source?: components["schemas"]["SourceKind"] | null;
                language?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    places_watches__watch_id__places_get: {
        parameters: {
            query?: {
                source?: components["schemas"]["SourceKind"] | null;
                language?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    themes_watches__watch_id__themes_get: {
        parameters: {
            query?: {
                source?: components["schemas"]["SourceKind"] | null;
                language?: string | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_for_watch_watches__watch_id__alerts_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                watch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOut_AlertOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_watches__watch_id__alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watch_id: string;
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
