from __future__ import annotations

from typing import Protocol, Sequence

from yimba.modules.watches.domain.model import Watch
from yimba.shared.pagination import Page, PageParams


class WatchRepository(Protocol):
    async def add(self, watch: Watch) -> None: ...

    async def get(self, watch_id: str) -> Watch | None: ...

    async def save(self, watch: Watch) -> None: ...

    async def delete(self, watch_id: str) -> None: ...

    async def slug_exists(self, owner_id: str, slug: str, *, excluding: str | None = None) -> bool: ...

    async def list_for_owner(self, owner_id: str, params: PageParams, search: str | None = None) -> Page[Watch]: ...

    async def list_active(self) -> Sequence[Watch]: ...
